"""
Maintain version for this package.
Do not edit this file, use 'version' section of config.
"""
# {# pkglts, version
#  -*- coding: utf-8 -*-

MAJOR = 1
"""(int) Version major component."""

MINOR = 0
"""(int) Version minor component."""

POST = 0
"""(int) Version post or bugfix component."""

__version__ = "{MAJOR:d}.{MINOR:d}.{POST:d}".format(MAJOR=MAJOR, MINOR=MINOR, POST=POST)
# #}
